# Generated by Django 5.0.6 on 2024-05-29 12:40

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('reading_time_in_minutes', models.IntegerField()),
                ('body', wagtail.fields.StreamField([('content', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul', 'hr'], template='blocks/richtext.html')), ('image', wagtail.images.blocks.ImageChooserBlock(template='blocks/image.html')), ('quote', wagtail.blocks.BlockQuoteBlock(template='blocks/quote.html')), ('twitter_block', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock()), ('author', wagtail.blocks.CharBlock())], template='blocks/twitter_block.html'))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
