# Generated by Django 5.0.6 on 2024-05-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FooterLinks',
            new_name='SocialMediaLinks',
        ),
    ]
